#!/usr/bin/with-contenv bash
set -e

usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

PROJECTDIR="/home/${S6_USER:-alpine}/project"; # set in Dockerfile
DATADIR="${DATADIR:-/home/$S6_USER/project/data}";

UPTIMEKUMA_ARGS="${UPTIMEKUMA_ARGS:- --data-dir=$DATADIR}";

cd "${PROJECTDIR}" || exit 1;

usercmd \
exec \
    node \
    server/server.js \
    ${UPTIMEKUMA_ARGS} \
    ;
